name: android_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - id: get-project
        name: Get project name
        run: echo "PROJECT=$(cat project-to-build)" >> $GITHUB_ENV

      - id: check-branch
        name: Check if branch is specified
        run: |
          if [[ "$PROJECT" == *"/tree/"* ]]; then
            echo "BRANCH=$(echo $PROJECT | sed 's|.*/tree/||')" >> $GITHUB_ENV
            echo "PROJECT=$(echo $PROJECT | sed 's|/tree/.*||')" >> $GITHUB_ENV
          else
            echo "BRANCH=main" >> $GITHUB_ENV
          fi

      - name: Clone project
        run: |
          if [ "$BRANCH" == "main" ]; then
            git clone --depth=1 ${{ env.PROJECT }} project
          else
            git clone --depth=1 --branch ${{ env.BRANCH }} ${{ env.PROJECT }} project
          fi

      - name: Set up Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build the app
        working-directory: ./project
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew assembleDefaultRelease --stacktrace --warning-mode all --info

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: my-build-apk
          path: ./**/*.apk
